package com.ideal.adp.whitelist.detail

import com.ideal.adp.whitelist.Field
import com.ideal.adp.whitelist.Whitelist._
import com.ideal.adp.whitelist.account.AccountType

class Qiyi extends LogicGenerable { 
override def load(): Unit = { 
    terminalWhitelist("1016675178", AccountType.IDFA,Field.Url,"iface.iqiyi.com", gen feature ("idfa") notContains("%") len(36,36))
    terminalWhitelist("-1030137109", AccountType.MDN,Field.Cookie,"ifacelog.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-1276403159", AccountType.IMEI,Field.Url,"iface2.iqiyi.com", gen feature ("device_id") )
    terminalWhitelist("1518970240", AccountType.IMEI,Field.Url,"suggest.video.qiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("49628329", AccountType.IMEI,Field.Url,"api.t.iqiyi.com", gen feature ("cupid_uid") )
    terminalWhitelist("-1433216275", AccountType.IMEI,Field.Url,"iface2.iqiyi.com", gen feature ("cupid_id") notContains("%") )
    terminalWhitelist("-1195418595", AccountType.MDN,Field.Cookie,"i.vip.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("-178646344", AccountType.IMEI,Field.Url,"score.video.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("1207825278", AccountType.MDN,Field.Cookie,"www.iqiyi.com", gen feature ("g_user_name") regex())
    terminalWhitelist("699199147", AccountType.IMEI,Field.Url,"subscription.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-202932693", AccountType.IMEI,Field.Url,"search.video.iqiyi.com", gen feature ("u") split("_",0) )
    terminalWhitelist("-1335427479", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("1361525375", AccountType.ANDROIDID,Field.Url,"iface.iqiyi.com", gen feature ("android_id") )
    terminalWhitelist("137244996", AccountType.ANDROIDID,Field.Url,"api.t.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("1128122539", AccountType.IMEI,Field.Url,"serv.vip.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-1450636912", AccountType.ANDROIDID,Field.Url,"iface.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-776549015", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("imei") )
    terminalWhitelist("-1022011903", AccountType.IMEI,Field.Url,"search.video.qiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-1485367413", AccountType.MDN,Field.Cookie,"serv.vip.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-1325456469", AccountType.IMEI,Field.Url,"search.video.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-1763000540", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("qyid") )
    terminalWhitelist("-1527575926", AccountType.ANDROIDID,Field.Url,"iface2.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-1535652406", AccountType.ANDROIDID,Field.Url,"emoticon.sns.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-973482677", AccountType.IMEI,Field.Url,"emoticon.sns.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("1577704874", AccountType.ANDROIDID,Field.Url,"mbdlog.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-1580202614", AccountType.ANDROIDID,Field.Url,"suggest.video.qiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-1589392109", AccountType.MDN,Field.Cookie,"serv.vip.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("1614431723", AccountType.MDN,Field.Cookie,"iface2.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("565600150", AccountType.IMEI,Field.Url,"serv.vip.iqiyi.com", gen feature ("id") )
    terminalWhitelist("1623055729", AccountType.MDN,Field.Cookie,"api.yuedu.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-2106949856", AccountType.IMEI,Field.Url,"serv.vip.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("1109996572", AccountType.IMEI,Field.Url,"l.rcd.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("-2100877881", AccountType.IMEI,Field.Url,"api.t.iqiyi.com", gen feature ("aqyid") split("_",0) add(AddUtilities.lstrip) )
    terminalWhitelist("1445736657", AccountType.IMEI,Field.Url,"api.t.iqiyi.com", gen feature ("m_device_id") )
    terminalWhitelist("-1694792918", AccountType.ANDROIDID,Field.Url,"serv.vip.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-1719840135", AccountType.MDN,Field.Cookie,"iface.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("-1774290466", AccountType.IMEI,Field.Url,"iface2.iqiyi.com", gen feature ("qyid") )
    terminalWhitelist("1770339990", AccountType.MDN,Field.Cookie,"www.iqiyi.com", gen feature ("user_name") regex())
    terminalWhitelist("-126842626", AccountType.IMEI,Field.Url,"serv.vip.iqiyi.com", gen feature ("qyid") )
    terminalWhitelist("1151035324", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("id") )
    terminalWhitelist("1282306822", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("-1854709781", AccountType.MDN,Field.Cookie,"file.yuedu.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-1869636336", AccountType.IDFA,Field.Url,"iface.iqiyi.com", gen feature ("cupid_uid") notContains("%") len(36,36))
    terminalWhitelist("-1877336693", AccountType.MDN,Field.Cookie,"subscription.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("1175049470", AccountType.IMEI,Field.Url,"mbdlog.iqiyi.com", gen feature ("qyid") )
    terminalWhitelist("1235316864", AccountType.IMEI,Field.Url,"iface2.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("-1892150385", AccountType.MDN,Field.Cookie,"l.rcd.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("-1946787813", AccountType.MDN,Field.Cookie,"www.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("175598481", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-385693273", AccountType.IMEI,Field.Url,"suggest.video.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("985937330", AccountType.IMEI,Field.Url,"data.video.qiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("2102975936", AccountType.IMEI,Field.Url,"emoticon.sns.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("2103529410", AccountType.ANDROIDID,Field.Url,"score.video.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("1059005245", AccountType.IMEI,Field.Url,"data.video.qiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("765564083", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("cupid_id") notContains("%") )
    terminalWhitelist("-256387343", AccountType.MDN,Field.Cookie,"iface.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("268034197", AccountType.MDN,Field.Cookie,"i.vip.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-307525846", AccountType.ANDROIDID,Field.Url,"subscription.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-309395597", AccountType.MDN,Field.Cookie,"iface2.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("3876396", AccountType.IMEI,Field.Url,"serv.vip.iqiyi.com", gen feature ("deviceID") )
    terminalWhitelist("-1545220853", AccountType.IMEI,Field.Url,"suggest.video.qiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-379205211", AccountType.MDN,Field.Cookie,"api.t.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("408281235", AccountType.MDN,Field.Cookie,"www.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("425681035", AccountType.MDN,Field.Cookie,"info.vip.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-428697593", AccountType.MDN,Field.Cookie,"l.rcd.iqiyi.com", gen feature ("P000email") regex())
    terminalWhitelist("-1820405875", AccountType.IMEI,Field.Url,"subscription.iqiyi.com", gen feature ("ckuid") )
    terminalWhitelist("-1651719552", AccountType.IMEI,Field.Url,"ifacelog.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("1180008474", AccountType.IMEI,Field.Url,"serv.vip.iqiyi.com", gen feature ("device_id") split("_",0) )
    terminalWhitelist("1046427895", AccountType.IMEI,Field.Url,"api.cupid.iqiyi.com", gen feature ("n") )
    terminalWhitelist("592640118", AccountType.IMEI,Field.Url,"search.video.qiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("1806728362", AccountType.IMEI,Field.Url,"i.vip.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("-1187236157", AccountType.IMEI,Field.Url,"score.video.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("1797686311", AccountType.IMEI,Field.Url,"l.rcd.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-539280696", AccountType.IMEI,Field.Url,"i.vip.iqiyi.com", gen feature ("qyid") )
    terminalWhitelist("585300956", AccountType.IDFA,Field.Url,"iface2.iqiyi.com", gen feature ("device_id") notContains("%") len(36,36))
    terminalWhitelist("616352531", AccountType.MDN,Field.Cookie,"subscription.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("635130056", AccountType.MAC,Field.Url,"iface.iqiyi.com", gen feature ("mac") )
    terminalWhitelist("-1793637811", AccountType.IMEI,Field.Url,"iface2.iqiyi.com", gen feature ("dev_imei") )
    terminalWhitelist("939336175", AccountType.IMEI,Field.Url,"data.video.qiyi.com", gen feature ("su") )
    terminalWhitelist("-694719251", AccountType.IDFA,Field.Url,"serv.vip.iqiyi.com", gen feature ("device_id") len(36,36))
    terminalWhitelist("814773280", AccountType.IMEI,Field.Url,"search.video.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("-372539857", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("device_id") )
    terminalWhitelist("-1710450390", AccountType.IMEI,Field.Url,"api.cupid.iqiyi.com", gen feature ("a") )
    terminalWhitelist("771275818", AccountType.ANDROIDID,Field.Url,"search.video.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-783699140", AccountType.ANDROIDID,Field.Url,"data.video.qiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("-845814884", AccountType.IMEI,Field.Url,"iface.iqiyi.com", gen feature ("uuid") )
    terminalWhitelist("-801222400", AccountType.ANDROIDID,Field.Url,"search.video.qiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("1845289953", AccountType.IMEI,Field.Url,"data.video.qiyi.com", gen feature ("qyid") split("_",0) )
    terminalWhitelist("882336820", AccountType.ANDROIDID,Field.Url,"i.vip.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("901327910", AccountType.ANDROIDID,Field.Url,"l.rcd.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("1282170635", AccountType.IMEI,Field.Url,"iface2.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("-493333973", AccountType.IMEI,Field.Url,"mbdlog.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("734833205", AccountType.IMEI,Field.Url,"i.vip.iqiyi.com", gen feature ("aqyid") split("_",0) notContains("%") )
    terminalWhitelist("103972640", AccountType.IMEI,Field.Url,"subscription.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("956607910", AccountType.ANDROIDID,Field.Url,"suggest.video.iqiyi.com", gen feature ("aqyid") split("_",1) len(13,16))
    terminalWhitelist("1339730820", AccountType.IMEI,Field.Url,"api.cupid.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("36523420", AccountType.IMEI,Field.Url,"suggest.video.iqiyi.com", gen feature ("cupid_uid") notContains("%") )
    terminalWhitelist("1931362223", AccountType.MDN,Field.Cookie,"cm.passport.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("368192107", AccountType.MDN,Field.Cookie,"i.vip.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("-1812130887", AccountType.MDN,Field.Cookie,"l.rcd.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("619558745", AccountType.MDN,Field.Cookie,"msg.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("-839805451", AccountType.MDN,Field.Cookie,"serv.vip.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("-276165899", AccountType.MDN,Field.Cookie,"subscription.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("203830039", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("g_user_name") )
    terminalWhitelist("-1058908764", AccountType.MDN,Field.Cookie,"act.vip.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("-676269668", AccountType.MDN,Field.Cookie,"api.cupid.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("-300760198", AccountType.MDN,Field.Cookie,"cm.passport.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("-1641167520", AccountType.MDN,Field.Cookie,"emoticon.sns.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("1698771236", AccountType.MDN,Field.Cookie,"msg.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("66591008", AccountType.MDN,Field.Cookie,"paopao.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("-125166972", AccountType.MDN,Field.Cookie,"suggest.video.iqiyi.com", gen feature ("P000email") )
    terminalWhitelist("437185698", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("P000%mail") )
    terminalWhitelist("-185374444", AccountType.MDN,Field.Cookie,"api.cupid.iqiyi.com", gen feature ("QC116") )
    terminalWhitelist("1883285458", AccountType.MDN,Field.Cookie,"api.yuedu.iqiyi.com", gen feature ("QC116") )
    terminalWhitelist("769441522", AccountType.MDN,Field.Cookie,"cm.passport.iqiyi.com", gen feature ("QC116") )
    terminalWhitelist("-2069816164", AccountType.MDN,Field.Cookie,"msg.iqiyi.com", gen feature ("QC116") )
    terminalWhitelist("58300924", AccountType.MDN,Field.Cookie,"suggest.video.iqiyi.com", gen feature ("QC116") )
    terminalWhitelist("-1791702054", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("QC116") )
    terminalWhitelist("-1420716649", AccountType.MDN,Field.Cookie,"cm.passport.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("524885075", AccountType.MDN,Field.Cookie,"i.vip.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("-1655437919", AccountType.MDN,Field.Cookie,"l.rcd.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("-1910907583", AccountType.MDN,Field.Cookie,"msg.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("-1389004323", AccountType.MDN,Field.Cookie,"serv.vip.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("-398489891", AccountType.MDN,Field.Cookie,"subscription.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("704691455", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("user_name") )
    terminalWhitelist("-694189590", AccountType.MDN,Field.Cookie,"act.vip.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("1126548210", AccountType.MDN,Field.Cookie,"api.cupid.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("966462760", AccountType.MDN,Field.Cookie,"api.t.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-1503074060", AccountType.MDN,Field.Cookie,"api.yuedu.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("787054766", AccountType.MDN,Field.Cookie,"cards.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("828909170", AccountType.MDN,Field.Cookie,"ckm.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("806687700", AccountType.MDN,Field.Cookie,"cm.passport.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("1977358990", AccountType.MDN,Field.Cookie,"cmts.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-520532818", AccountType.MDN,Field.Cookie,"emoticon.sns.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-146548626", AccountType.MDN,Field.Cookie,"iface2.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("1289817716", AccountType.MDN,Field.Cookie,"iface.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-171567250", AccountType.MDN,Field.Cookie,"ifacelog.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("1043093898", AccountType.MDN,Field.Cookie,"l.rcd.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-446234006", AccountType.MDN,Field.Cookie,"msg.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-637824274", AccountType.MDN,Field.Cookie,"paopao.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-1712507890", AccountType.MDN,Field.Cookie,"serv.vip.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("608931342", AccountType.MDN,Field.Cookie,"subscription.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-1165449462", AccountType.MDN,Field.Cookie,"suggest.video.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("1832751596", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-674976746", AccountType.MDN,Field.Cookie,"www.iqiyi.com", gen feature ("P00002") urlDecode() jsonToMap() find("user_name"))
    terminalWhitelist("-1835747780", AccountType.MDN,Field.Cookie,"cm.passport.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("-1966953370", AccountType.MDN,Field.Cookie,"msg.iqiyi.com", gen feature ("QC116") regex())
    terminalWhitelist("-749112028", AccountType.MDN,Field.Cookie,"t7z.cupid.iqiyi.com", gen feature ("QC116") regex())
	}
}