package com.ideal.adp.whitelist.detail

import com.ideal.adp.whitelist.Field
import com.ideal.adp.whitelist.Whitelist._
import com.ideal.adp.whitelist.account.AccountType
/**
 * Created by jason on 2017-03-13.
 */
class Temp extends LogicGenerable{
  override def load(): Unit = {

    //需要写方法
    //terminalWhitelist("-1208063143", AccountType.MAC, Field.Url, "api.m.taobao.com", gen feature("data") urlDecode() jsonToMap())
    //terminalWhitelist("-1267138300", AccountType.IMEI, Field.Url, "platform.sina.com.cn", gen feature("pdps_params") )
    //完整
    terminalWhitelist("-1182215947", AccountType.MDN, Field.Cookie, "ju.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("-1192586425", AccountType.IMEI, Field.Url, "iface2.iqiyi.com", gen feature("cupid_id") )
    terminalWhitelist("-1193122891", AccountType.IMEI, Field.Url, "stat.funshion.net", gen feature("imei_id") )
    terminalWhitelist("-1195418595", AccountType.MDN, Field.Cookie, "i.vip.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("1198242383", AccountType.MDN, Field.Cookie, "api.m.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("-1198549941", AccountType.IMEI, Field.Url, "ark.letv.com", gen feature("d") )
    terminalWhitelist("1198883420", AccountType.IMEI, Field.Url, "score.video.iqiyi.com", gen feature("cupid_uid") )
    terminalWhitelist("1205995314", AccountType.IMEI, Field.Url, "iface2.iq", gen feature("cupid_uid") )
    terminalWhitelist("-120609193", AccountType.MDN, Field.Cookie, "member.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("1207825278", AccountType.MDN, Field.Cookie, "www.iqiyi.com", gen feature("g_user_name") regex())
    terminalWhitelist("-1215158962", AccountType.MAC, Field.Url, "portal.wietone.com", gen feature("mac") )
    terminalWhitelist("1215182363", AccountType.ANDROIDID, Field.Url, "login.wz.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("1222115737", AccountType.MAC, Field.Url, "g.alicdn.com", gen feature("usermac") urlDecode())
    terminalWhitelist("400200409", AccountType.MAC, Field.Cookie, "in.m.jd.com", gen feature("pre_session") split("\\|", 0) split("-", 1))
    terminalWhitelist("1229510333", AccountType.IMEI, Field.Url, "susapi.lenovomm.com", gen feature("dauuid") )
    terminalWhitelist("-1229987005", AccountType.MDN, Field.Url, "221.179.11.196", gen feature("WT.gd_mobile") regex())
    terminalWhitelist("-1236130171", AccountType.ANDROIDID, Field.Url, "www.babytree.com", gen feature("android_id") )
    terminalWhitelist("-1242739556", AccountType.IMEI, Field.Url, "iface", gen feature("qyid") )
    terminalWhitelist("1247618633", AccountType.IMEI, Field.Url, "subscription.iqiyi.com", gen feature("aqyid") split("_", 0))
    terminalWhitelist("-1248907678", AccountType.MAC, Field.Url, "api.k.sohu.com", gen feature("wifi_bssid") )
    terminalWhitelist("-1250572513", AccountType.IMEI, Field.Url, "tj.coolyun.com", gen feature("uid") )
    terminalWhitelist("-1251828207", AccountType.IMEI, Field.Url, "aa0.pub.funshion.com", gen feature("imei") )
    terminalWhitelist("-1253659946", AccountType.MDN, Field.Cookie, "weidian.com", gen feature("WD_b_tele") regex())
    terminalWhitelist("1257860819", AccountType.MDN, Field.Cookie, "favorite.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("125948682", AccountType.IMEI, Field.Url, "show.m.mediav.com", gen feature("imei") )
    terminalWhitelist("1259855496", AccountType.IMEI, Field.Url, "dabao.meituan.com", gen feature("utm_content") )

    //android all
    terminalWhitelist("-1271221085", AccountType.ANDROIDID, Field.Url, "api.diditaxi.com.cn", gen feature("android_id") )
    terminalWhitelist("-1303801403", AccountType.ANDROIDID, Field.Url, "busybox.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("1316287761", AccountType.ANDROIDID, Field.Url, "appsupport.qq.com", gen feature("android_id") )
    terminalWhitelist("1361525375", AccountType.ANDROIDID, Field.Url, "iface.iqiyi.com", gen feature("android_id") )
    terminalWhitelist("1567161820", AccountType.ANDROIDID, Field.Url, "show.m.mediav.com", gen feature("androidid") )
    terminalWhitelist("1577190373", AccountType.ANDROIDID, Field.Url, "common.diditaxi.com.cn", gen feature("android_id") )
    terminalWhitelist("1632629522", AccountType.ANDROIDID, Field.Url, "tq.91.com", gen feature("androidid") )
    terminalWhitelist("-1667344059", AccountType.ANDROIDID, Field.Url, "slave2.mercury.kakamobi.cn", gen feature("_androidId") )
    terminalWhitelist("1733427384", AccountType.ANDROIDID, Field.Url, "114.80.165.113", gen feature("androidid") )
    terminalWhitelist("1738707868", AccountType.ANDROIDID, Field.Url, "s.go.sohu.com", gen feature("AndroidID") )
    terminalWhitelist("1787552947", AccountType.ANDROIDID, Field.Url, "traffic.wz.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("-1788176629", AccountType.ANDROIDID, Field.Url, "imp.gentags.net", gen feature("android_id") )
    terminalWhitelist("187591864", AccountType.ANDROIDID, Field.Url, "agn.aty.sohu.com", gen feature("AndroidID") )
    terminalWhitelist("1958083610", AccountType.ANDROIDID, Field.Url, "mapi.dianping.com", gen feature("androidid") )
    terminalWhitelist("-1959690212", AccountType.ANDROIDID, Field.Url, "weather.moxiu.net", gen feature("androidID") )
    terminalWhitelist("2123148754", AccountType.ANDROIDID, Field.Url, "gcapi.adpush.cn", gen feature("ANDROIDID") )
    terminalWhitelist("235032069", AccountType.ANDROIDID, Field.Url, "w.inews.qq.com", gen feature("android_id") )
    terminalWhitelist("247968792", AccountType.ANDROIDID, Field.Url, "api.k.sohu.com", gen feature("AndroidID") )
    terminalWhitelist("278887064", AccountType.ANDROIDID, Field.Url, "v.admaster.com.cn", gen feature("ANDROIDID") )
    terminalWhitelist("-369028291", AccountType.ANDROIDID, Field.Url, "stat.funshion.net", gen feature("android_id") )
    terminalWhitelist("-370569394", AccountType.ANDROIDID, Field.Url, "btrace.qq.com", gen feature("androidid") )
    terminalWhitelist("-389128425", AccountType.ANDROIDID, Field.Url, "g.cn.miaozhen.com", gen feature("android_id") )
    terminalWhitelist("-392707163", AccountType.ANDROIDID, Field.Url, "v.admaster.com.cn", gen feature("android_id") )
    terminalWhitelist("394294261", AccountType.ANDROIDID, Field.Url, "api.didialift.com", gen feature("android_id") )
    terminalWhitelist("464413221", AccountType.ANDROIDID, Field.Url, "atk.gxb.cnzz.com", gen feature("android_id") )
    terminalWhitelist("-505008035", AccountType.ANDROIDID, Field.Url, "query.wz.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("-522387419", AccountType.ANDROIDID, Field.Url, "smart.789.kakamobi.cn", gen feature("_androidId") )
    terminalWhitelist("551724517", AccountType.ANDROIDID, Field.Url, "qichezhijia.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("-658053339", AccountType.ANDROIDID, Field.Url, "api.udache.com", gen feature("android_id") )
    terminalWhitelist("669100677", AccountType.ANDROIDID, Field.Url, "notice.diditaxi.com.cn", gen feature("android_id") )
    terminalWhitelist("-690649874", AccountType.ANDROIDID, Field.Url, "e.cn.miaozhen.com", gen feature("androidid") )
    terminalWhitelist("741238891", AccountType.ANDROIDID, Field.Url, "cheyouquan.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("751724976", AccountType.ANDROIDID, Field.Url, "i.go.sohu.com", gen feature("AndroidID") )
    terminalWhitelist("783957711", AccountType.ANDROIDID, Field.Url, "config.kakamobi.com", gen feature("_androidId") )
    terminalWhitelist("890797414", AccountType.ANDROIDID, Field.Url, "log.ycapp.yiche.com", gen feature("androidId") )
    terminalWhitelist("964163634", AccountType.ANDROIDID, Field.Url, "api.sina.cn", gen feature("AndroidID") )

    terminalWhitelist("-132157590", AccountType.ANDROIDID, Field.Url, "i", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1361172892", AccountType.ANDROIDID, Field.Url, "iface", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("137244996", AccountType.ANDROIDID, Field.Url, "api.t.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("1438326058", AccountType.ANDROIDID, Field.Url, "ifac", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1450636912", AccountType.ANDROIDID, Field.Url, "iface.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1491677268", AccountType.ANDROIDID, Field.Url, "iface2.iq", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1527575926", AccountType.ANDROIDID, Field.Url, "iface2.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1535652406", AccountType.ANDROIDID, Field.Url, "emoticon.sns.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("1577704874", AccountType.ANDROIDID, Field.Url, "mbdlog.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1580202614", AccountType.ANDROIDID, Field.Url, "suggest.video.qiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-1694792918", AccountType.ANDROIDID, Field.Url, "serv.vip.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("1800492010", AccountType.ANDROIDID, Field.Url, "if", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("2103529410", AccountType.ANDROIDID, Field.Url, "score.video.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("238772522", AccountType.ANDROIDID, Field.Url, "wlan.ct10000.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-307525846", AccountType.ANDROIDID, Field.Url, "subscription.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("464543456", AccountType.ANDROIDID, Field.Url, "ifa", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-47289004", AccountType.ANDROIDID, Field.Url, "irs01.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("726207754", AccountType.ANDROIDID, Field.Url, "iface2", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("771275818", AccountType.ANDROIDID, Field.Url, "search.video.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-783699140", AccountType.ANDROIDID, Field.Url, "data.video.qiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-801222400", AccountType.ANDROIDID, Field.Url, "search.video.qiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("882336820", AccountType.ANDROIDID, Field.Url, "i.vip.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("901327910", AccountType.ANDROIDID, Field.Url, "l.rcd.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("-930909398", AccountType.ANDROIDID, Field.Url, "iface2.i", gen feature("aqyid") split("_", 1) len(13,16))
    terminalWhitelist("956607910", AccountType.ANDROIDID, Field.Url, "suggest.video.iqiyi.com", gen feature("aqyid") split("_", 1) len(13,16))

    terminalWhitelist("-449156898", AccountType.ANDROIDID, Field.Url, "t.cr-nielsen.com", gen feature("ANDROIDID") len(13,16))
    terminalWhitelist("-991656578", AccountType.ANDROIDID, Field.Url, "i", gen feature("androidid") len(13,16))

    terminalWhitelist("-181050644", AccountType.ANDROIDID, Field.Url, "irs01.com?hvt", gen feature("androidid") notContains("%"))
    terminalWhitelist("-1813271916", AccountType.ANDROIDID, Field.Url, "qq.irs01.com", gen feature("androidid") notContains("%"))
    //mac
    terminalWhitelist("-1495956879", AccountType.MAC, Field.Url, "m.baidu.com", gen feature("clientmac") )
    terminalWhitelist("-1518292626", AccountType.MAC, Field.Url, "cdn.exands.com", gen feature("mac") )
    terminalWhitelist("1574151598", AccountType.MAC, Field.Url, "aa1.pub.funshion.com", gen feature("mac") )
    terminalWhitelist("1578006309", AccountType.MAC, Field.Url, "mapi.dianping.com", gen feature("wifimac") )
    terminalWhitelist("159237582", AccountType.MAC, Field.Url, "qq.irs01.com", gen feature("mac") )
    terminalWhitelist("164610766", AccountType.MAC, Field.Url, "121.40.190.129", gen feature("mac") )
    terminalWhitelist("-1650321976", AccountType.MAC, Field.Url, "portal.wietone.com:80", gen feature("mac") )
    terminalWhitelist("1651041902", AccountType.MAC, Field.Url, "common.diditaxi.com.cn", gen feature("mac") )
    terminalWhitelist("1741474062", AccountType.MAC, Field.Url, "agn.aty.sohu.com", gen feature("mac") )
    terminalWhitelist("-1749511720", AccountType.MAC, Field.Url, "auth.greenwifi.com.cn", gen feature("mac") )
    terminalWhitelist("1754861443", AccountType.MAC, Field.Url, "albs.moji001.com", gen feature("wifimac") )
    terminalWhitelist("-1826113987", AccountType.MAC, Field.Url, "apple.www.letv.com", gen feature("wmac") )
    terminalWhitelist("-1920492987", AccountType.MAC, Field.Url, "tyaqy.m.cn.miaozhen.com", gen feature("m7") )
    terminalWhitelist("-1949815987", AccountType.MAC, Field.Url, "pos.baidu.com", gen feature("udi") )
    terminalWhitelist("-1952596954", AccountType.MAC, Field.Url, "m.baidu.com", gen feature("mac") )
    terminalWhitelist("-1971935346", AccountType.MAC, Field.Url, "api.3g.tudou.com", gen feature("mac") )
    terminalWhitelist("-2105459939", AccountType.MAC, Field.Url, "ark.letv.com", gen feature("wmac") )
    terminalWhitelist("2109400058", AccountType.MAC, Field.Url, "cfg.adsmogo.com", gen feature("mac") )
    terminalWhitelist("2135309710", AccountType.MAC, Field.Url, "adapi.hiwemeet.com", gen feature("mac") )
    terminalWhitelist("-281387005", AccountType.MAC, Field.Url, "114.80.165.113", gen feature("wifimac") )
    terminalWhitelist("-390618087", AccountType.MAC, Field.Url, "imageplus.baidu.com", gen feature("clid") )
    terminalWhitelist("474368512", AccountType.MAC, Field.Url, "wifiapi02.51y5.net", gen feature("bssid") )
    terminalWhitelist("-539256178", AccountType.MAC, Field.Url, "w21.100msh.com", gen feature("mac") )
    terminalWhitelist("635130056", AccountType.MAC, Field.Url, "iface.iqiyi.com", gen feature("mac") )
    terminalWhitelist("-645291174", AccountType.MAC, Field.Url, "wiportal.wiwide.com", gen feature("called") )
    terminalWhitelist("652888052", AccountType.MAC, Field.Url, "cfg.adsmogo.org", gen feature("mac") )
    terminalWhitelist("695201902", AccountType.MAC, Field.Url, "imp.adsmogo.mobi", gen feature("mac") )
    terminalWhitelist("-706183474", AccountType.MAC, Field.Url, "market.hiapk.com", gen feature("mac") )
    terminalWhitelist("742952206", AccountType.MAC, Field.Url, "notice.diditaxi.com.cn", gen feature("mac") )
    terminalWhitelist("797828034", AccountType.MAC, Field.Url, "mc.funshion.com", gen feature("mac") )
    terminalWhitelist("-80198032", AccountType.MAC, Field.Url, "wiportal.wiwide.com", gen feature("mac") )
    terminalWhitelist("82669811", AccountType.MAC, Field.Cookie, "www.jumei.com", gen feature("mac") )
    terminalWhitelist("-922135870", AccountType.MAC, Field.Url, "cfg.adsmogo.net", gen feature("mac") )
    terminalWhitelist("-92354615", AccountType.MAC, Field.Cookie, "track.adsage.com", gen feature("cookie_uid") )
    terminalWhitelist("-99443971", AccountType.MAC, Field.Url, "g.cn.miaozhen.com", gen feature("m7") )

    terminalWhitelist("1268159193", AccountType.MAC, Field.Url, "market.hiapk.com", gen feature("userMac") urlDecode())
    terminalWhitelist("-1300513962", AccountType.MAC, Field.Url, "user-mobile.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("1343290382", AccountType.MAC, Field.Url, "loc.map.baidu.com", gen feature("mac") urlDecode())
    terminalWhitelist("143462891", AccountType.MAC, Field.Url, "ipip.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("1462402656", AccountType.MAC, Field.Url, "mapi.yhd.com", gen feature("ap_id") urlDecode())
    terminalWhitelist("1472747618", AccountType.MAC, Field.Url, "vapi.changba.com", gen feature("macaddress") urlDecode())
    terminalWhitelist("1502222851", AccountType.MAC, Field.Url, "adm.myzaker.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-1502669466", AccountType.MAC, Field.Url, "wn.x.jd.com", gen feature("mac") urlDecode())
    terminalWhitelist("-1560289852", AccountType.MAC, Field.Url, "bksdkconfig.video.qq.com", gen feature("mac") urlDecode())
    terminalWhitelist("-1590598012", AccountType.MAC, Field.Url, "push.m.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("-1681549253", AccountType.MAC, Field.Url, "sapi.beibei.com", gen feature("usermac") urlDecode())
    terminalWhitelist("-1698790284", AccountType.MAC, Field.Url, "ad.api.3g.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("1714584765", AccountType.MAC, Field.Url, "ex.puata.info", gen feature("mc") urlDecode())
    terminalWhitelist("1735896799", AccountType.MAC, Field.Url, "traffic.wz.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("174168131", AccountType.MAC, Field.Url, "config.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("1750106541", AccountType.MAC, Field.Url, "smart.789.kakamobi.cn", gen feature("_mac") urlDecode())
    terminalWhitelist("176436148", AccountType.MAC, Field.Url, "detail.api.mobile.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("1778834614", AccountType.MAC, Field.Url, "api.changba.com", gen feature("macaddress") urlDecode())
    terminalWhitelist("-1829817154", AccountType.MAC, Field.Url, "mapi.appvipshop.com", gen feature("mac") urlDecode())
    terminalWhitelist("-1849428584", AccountType.MAC, Field.Url, "cdn.exands.com", gen feature("client_MAC") urlDecode())
    terminalWhitelist("1910122258", AccountType.MAC, Field.Url, "down.api.mobile.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("1951329729", AccountType.MAC, Field.Url, "jupiter.kakamobi.cn", gen feature("_mac") urlDecode())
    terminalWhitelist("-1973101384", AccountType.MAC, Field.Url, "mapi.yhd.com", gen feature("client_mac") urlDecode())
    terminalWhitelist("1982714861", AccountType.MAC, Field.Url, "qichezhijia.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-2006099851", AccountType.MAC, Field.Url, "query.wz.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-2057743644", AccountType.MAC, Field.Url, "sdkconfig.video.qq.com", gen feature("mac") urlDecode())
    terminalWhitelist("-2067467420", AccountType.MAC, Field.Url, "android.wochacha.com", gen feature("mac") urlDecode())
    terminalWhitelist("2085230404", AccountType.MAC, Field.Url, "ic.snssdk.com", gen feature("mac") urlDecode())
    terminalWhitelist("-2099182424", AccountType.MAC, Field.Url, "service.cocounion.com", gen feature("rm") urlDecode())
    terminalWhitelist("-219805065", AccountType.MAC, Field.Url, "login.wz.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-235873628", AccountType.MAC, Field.Url, "w.cnews.qq.com", gen feature("mac") urlDecode())
    terminalWhitelist("26332102", AccountType.MAC, Field.Url, "api.diditaxi.com.cn", gen feature("mac") urlDecode())
    terminalWhitelist("273248612", AccountType.MAC, Field.Url, "v.gdt.qq.com", gen feature("mac") urlDecode())
    terminalWhitelist("-277515740", AccountType.MAC, Field.Url, "user.api.3g.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("-309016381", AccountType.MAC, Field.Url, "datanerd.wz.kakamobi.cn", gen feature("_mac") urlDecode())
    terminalWhitelist("316549365", AccountType.MAC, Field.Url, "update.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-357308540", AccountType.MAC, Field.Url, "common.diditaxi.com.cn", gen feature("mac") urlDecode())
    terminalWhitelist("-396423452", AccountType.MAC, Field.Url, "aa0.pub.funshion.com", gen feature("mac") urlDecode())
    terminalWhitelist("397002361", AccountType.MAC, Field.Url, "g.alicdn.com", gen feature("clientMac") urlDecode())
    terminalWhitelist("400320670", AccountType.MAC, Field.Url, "hd.api.mobile.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("-408866908", AccountType.MAC, Field.Url, "api.mobile.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("423862775", AccountType.MAC, Field.Url, "789.kakamobi.cn", gen feature("_mac") urlDecode())
    terminalWhitelist("-444703380", AccountType.MAC, Field.Url, "wise.qq.com", gen feature("mac") urlDecode())
    terminalWhitelist("530682476", AccountType.MAC, Field.Url, "i.go.sohu.com", gen feature("mac") urlDecode())
    terminalWhitelist("-551062283", AccountType.MAC, Field.Url, "market.hiapk.com", gen feature("apMac") urlDecode())
    terminalWhitelist("562797572", AccountType.MAC, Field.Url, "r.cnews.qq.com", gen feature("mac") urlDecode())
    terminalWhitelist("63048845", AccountType.MAC, Field.Url, "slave2.mercury.kakamobi.cn", gen feature("_mac") urlDecode())
    terminalWhitelist("-635067865", AccountType.MAC, Field.Url, "cheyouquan.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-659080228", AccountType.MAC, Field.Url, "sapi.beibei.com", gen feature("u_mac") urlDecode())
    terminalWhitelist("-671432574", AccountType.MAC, Field.Url, "timeline.api.changba.com", gen feature("macaddress") urlDecode())
    terminalWhitelist("716880141", AccountType.MAC, Field.Url, "ai.kakamobi.cn", gen feature("_mac") urlDecode())
    terminalWhitelist("-743349235", AccountType.MAC, Field.Url, "busybox.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("-747696332", AccountType.MAC, Field.Url, "ad.api.3g.tudou.com", gen feature("mac") urlDecode())
    terminalWhitelist("-819344307", AccountType.MAC, Field.Url, "telepathy.kakamobi.com", gen feature("_mac") urlDecode())
    terminalWhitelist("852286925", AccountType.MAC, Field.Url, "api.platform.letv.com", gen feature("macaddr") urlDecode())
    terminalWhitelist("-855171164", AccountType.MAC, Field.Url, "rec.api.gamex.mobile.youku.com", gen feature("mac") urlDecode())
    terminalWhitelist("-863445950", AccountType.MAC, Field.Url, "gapi.changba.com", gen feature("macaddress") urlDecode())
    terminalWhitelist("-895853795", AccountType.MAC, Field.Url, "g.alicdn.com", gen feature("gw_mac") urlDecode())
    terminalWhitelist("99282768", AccountType.MAC, Field.Url, "adnewnc.app.autohome.com.cn", gen feature("mac") urlDecode())
    terminalWhitelist("1511398098", AccountType.MAC, Field.Url, "dc.letv.com", gen feature("auid") urlDecode())
    terminalWhitelist("-1986747468", AccountType.MAC, Field.Url, "track.adsage.com", gen feature("uid") urlDecode())
    terminalWhitelist("-228043435", AccountType.MAC, Field.Url, "wlan.ct10000.com", gen feature("mac") urlDecode())
    terminalWhitelist("-408260822", AccountType.MAC, Field.Url, "dc.letv.com", gen feature("mac") urlDecode())
    terminalWhitelist("-512831429", AccountType.MAC, Field.Url, "irs01.com", gen feature("mac") urlDecode())
    terminalWhitelist("975266590", AccountType.MAC, Field.Url, "log.umtrack.com", gen feature("mac") urlDecode())

    terminalWhitelist("1544314041", AccountType.MAC, Field.Url, "like.video.qq.com", gen feature("mta") )
    terminalWhitelist("-1552362488", AccountType.MAC, Field.Cookie, "server.mafengwo.cn", gen feature("__openudid") )
    terminalWhitelist("225070219", AccountType.MAC, Field.Url, "tj.coolyun.com", gen feature("uid") )
    terminalWhitelist("288210828", AccountType.MAC, Field.Cookie, "mapi.mafengwo.cnhttps", gen feature("__openudid") )
    terminalWhitelist("-348792002", AccountType.MAC, Field.Cookie, "www.mafengwo.cn", gen feature("__openudid") )
    terminalWhitelist("373481192", AccountType.MAC, Field.Cookie, "www.mafengwo.cnhttps", gen feature("__openudid") )
    terminalWhitelist("-396805381", AccountType.MAC, Field.Url, "w.51tv.com", gen feature("usercode") )
    terminalWhitelist("-421013524", AccountType.MAC, Field.Url, "update.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("-523483128", AccountType.MAC, Field.Cookie, "mapi.mafengwo.cn", gen feature("__openudid") )
    terminalWhitelist("-744431440", AccountType.MAC, Field.Url, "weather.moxiu.net", gen feature("mac") )
    terminalWhitelist("951548829", AccountType.MAC, Field.Url, "w.51tv.com", gen feature("username") )
    terminalWhitelist("-2042016313", AccountType.MAC, Field.Url, "apple.www.letv.com", gen feature("mac") )
    //imei
    terminalWhitelist("1268595665", AccountType.IMEI, Field.Url, "adnewnc.app.autohome.com.cn", gen feature("deviceid") )
    terminalWhitelist("-1285391165", AccountType.IMEI, Field.Url, "cheyouquan.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("1402732098", AccountType.IMEI, Field.Url, "tyaqy.m.cn.miaozhen.com", gen feature("m3") )
    terminalWhitelist("-1419574211", AccountType.IMEI, Field.Url, "qichezhijia.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("1489647219", AccountType.IMEI, Field.Url, "login.wz.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("1708771357", AccountType.IMEI, Field.Url, "busybox.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("-1780140820", AccountType.IMEI, Field.Url, "wise.qq.com", gen feature("devid") )
    terminalWhitelist("1917355174", AccountType.IMEI, Field.Url, "imp.adsmogo.mobi", gen feature("imei") )
    terminalWhitelist("-1919419316", AccountType.IMEI, Field.Url, "fun.m.cn.miaozhen.com", gen feature("m3") )
    terminalWhitelist("-1997957894", AccountType.IMEI, Field.Url, "cfg.adsmogo.net", gen feature("imei") )
    terminalWhitelist("2140674982", AccountType.IMEI, Field.Url, "push.m.youku.com", gen feature("imei") )
    terminalWhitelist("-230543179", AccountType.IMEI, Field.Url, "query.wz.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("-239077109", AccountType.IMEI, Field.Url, "traffic.wz.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("-247922563", AccountType.IMEI, Field.Url, "smart.789.kakamobi.cn", gen feature("_imei") )
    terminalWhitelist("-336991267", AccountType.IMEI, Field.Url, "telepathy.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("412601245", AccountType.IMEI, Field.Url, "slave2.mercury.kakamobi.cn", gen feature("_imei") )
    terminalWhitelist("-422933972", AccountType.IMEI, Field.Url, "cfg.adsmogo.org", gen feature("imei") )
    terminalWhitelist("461700756", AccountType.IMEI, Field.Url, "user-mobile.youku.com", gen feature("imei") )
    terminalWhitelist("-577991354", AccountType.IMEI, Field.Url, "notice.diditaxi.com.cn", gen feature("imei") )
    terminalWhitelist("61934644", AccountType.IMEI, Field.Url, "w.cnews.qq.com", gen feature("devid") )
    terminalWhitelist("-651511162", AccountType.IMEI, Field.Url, "rec.api.gamex.mobile.youku.com", gen feature("imei") )

    terminalWhitelist("-1354177260", AccountType.IMEI, Field.Url, "iface2", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("1510126759", AccountType.IMEI, Field.Url, "iface2.i", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-1558213049", AccountType.IMEI, Field.Url, "iface2", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("1631622900", AccountType.IMEI, Field.Url, "serv.vip.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-1634230408", AccountType.IMEI, Field.Url, "l.rcd.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-1656207961", AccountType.IMEI, Field.Url, "iface2.iqi", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("1700593504", AccountType.IMEI, Field.Url, "qq.irs01.com", gen feature("imei") notContains("%"))
    terminalWhitelist("171163173", AccountType.IMEI, Field.Url, "iface2.iq", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-1767937433", AccountType.IMEI, Field.Url, "if", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-1825103154", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-1886813804", AccountType.IMEI, Field.Url, "iface2.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("1971458484", AccountType.IMEI, Field.Url, "i", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-2003800332", AccountType.IMEI, Field.Url, "ifac", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-2085868638", AccountType.IMEI, Field.Url, "data.video.qiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-2086380460", AccountType.IMEI, Field.Url, "emoticon.sns.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-2143622006", AccountType.IMEI, Field.Url, "irs01.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-251198143", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-254157580", AccountType.IMEI, Field.Url, "iface2.i", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("36918001", AccountType.IMEI, Field.Url, "ifa", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-38164057", AccountType.IMEI, Field.Url, "ifac", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-394291347", AccountType.IMEI, Field.Url, "iface", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("414858618", AccountType.IMEI, Field.Url, "iface", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("421453364", AccountType.IMEI, Field.Url, "if", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-435286361", AccountType.IMEI, Field.Url, "i", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-46462058", AccountType.IMEI, Field.Url, "irs01.com", gen feature("imei") notContains("%"))
    terminalWhitelist("-471765100", AccountType.IMEI, Field.Url, "ifacelog.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-492501122", AccountType.IMEI, Field.Url, "ifa", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-506678462", AccountType.IMEI, Field.Url, "iface2.", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("511476574", AccountType.IMEI, Field.Url, "search.video.qiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("548241322", AccountType.IMEI, Field.Url, "i.vip.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("680034164", AccountType.IMEI, Field.Url, "iface2.iqi", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-712261132", AccountType.IMEI, Field.Url, "search.video.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-92760332", AccountType.IMEI, Field.Url, "subscription.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("967870736", AccountType.IMEI, Field.Url, "api.cupid.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("983423925", AccountType.IMEI, Field.Url, "iface2.", gen feature("cupid_id") notContains("%"))
    terminalWhitelist("-995658248", AccountType.IMEI, Field.Url, "suggest.video.iqiyi.com", gen feature("cupid_uid") notContains("%"))

    terminalWhitelist("-1392108589", AccountType.IMEI, Field.Url, "ifa", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-1421570999", AccountType.IMEI, Field.Url, "serv.vip.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-1478630221", AccountType.IMEI, Field.Url, "search.video.qiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-148631223", AccountType.IMEI, Field.Url, "search.video.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("1530366281", AccountType.IMEI, Field.Url, "ifac", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("154624937", AccountType.IMEI, Field.Url, "emoticon.sns.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-169009335", AccountType.IMEI, Field.Url, "wlan.ct10000.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-1792929463", AccountType.IMEI, Field.Url, "iface2.i", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-1953305721", AccountType.IMEI, Field.Url, "iface2.iq", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("2033895715", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-2036021043", AccountType.IMEI, Field.Url, "suggest.video.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-2125529865", AccountType.IMEI, Field.Url, "data.video.qiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-355449879", AccountType.IMEI, Field.Url, "suggest.video.qiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-484182935", AccountType.IMEI, Field.Url, "iface2", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("571419953", AccountType.IMEI, Field.Url, "score.video.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("573677133", AccountType.IMEI, Field.Url, "l.rcd.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-650235441", AccountType.IMEI, Field.Url, "iface", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-707723625", AccountType.IMEI, Field.Url, "iface2.", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-740730743", AccountType.IMEI, Field.Url, "i", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-912985623", AccountType.IMEI, Field.Url, "iface2.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("914617033", AccountType.IMEI, Field.Url, "mbdlog.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))
    terminalWhitelist("-917040897", AccountType.IMEI, Field.Url, "i.vip.iqiyi.com", gen feature("aqyid") split("_", 0) notContains("%"))

    terminalWhitelist("-1277437757", AccountType.IMEI, Field.Url, "weather.vivo.com.cn", gen feature("imei") )
    terminalWhitelist("-1307551530", AccountType.IMEI, Field.Url, "platform.sina.com.cn", gen feature("token") )
    terminalWhitelist("130911715", AccountType.IMEI, Field.Url, "dynamic.user.app.m.letv.com", gen feature("imei") )
    terminalWhitelist("-1310372847", AccountType.IMEI, Field.Url, "agn.aty.sohu.com", gen feature("imei") )
    terminalWhitelist("-1319738575", AccountType.IMEI, Field.Url, "bksdkconfig.video.qq.com", gen feature("imei") )
    terminalWhitelist("-1324143293", AccountType.IMEI, Field.Url, "api3g2.lvmama.com", gen feature("udid") )
    terminalWhitelist("1345392254", AccountType.IMEI, Field.Url, "stat.10jqka.com.cn", gen feature("uuid") )
    terminalWhitelist("-1353532960", AccountType.IMEI, Field.Url, "api3g2.lvmama.com", gen feature("deviceToken") )
    terminalWhitelist("1377181711", AccountType.IMEI, Field.Url, "ads.wapx.cn", gen feature("udid") )
    terminalWhitelist("1385070759", AccountType.IMEI, Field.Url, "impservice.dictapp.youdao.com", gen feature("imei") )
    terminalWhitelist("1392681504", AccountType.IMEI, Field.Url, "th.suning.com", gen feature("dev_id") )
    terminalWhitelist("1400284847", AccountType.IMEI, Field.Url, "android.wochacha.com", gen feature("udid") )
    terminalWhitelist("1420540192", AccountType.IMEI, Field.Url, "ifa", gen feature("qyid") )
    terminalWhitelist("-1428219023", AccountType.IMEI, Field.Url, "dynamic.app.m.letv.com", gen feature("imei") )
    terminalWhitelist("1430637015", AccountType.IMEI, Field.Url, "api.map.baidu.com", gen feature("im") )
    terminalWhitelist("1435126366", AccountType.IMEI, Field.Url, "dm.toutiao.com", gen feature("uuid") )
    terminalWhitelist("-1446717967", AccountType.IMEI, Field.Url, "mcgi.play.cp81.ott.cibntv.net", gen feature("device_id") )
    terminalWhitelist("1460564777", AccountType.IMEI, Field.Url, "m.baidu.com", gen feature("imei") )
    terminalWhitelist("1476841035", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("imei") )
    terminalWhitelist("1487300179", AccountType.IMEI, Field.Url, "touch.qunar.com", gen feature("uid") )
    terminalWhitelist("1504961790", AccountType.IMEI, Field.Url, "ggs.myzaker.com", gen feature("_udid") )
    terminalWhitelist("1505474928", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("qyid") )
    terminalWhitelist("-1509985964", AccountType.IMEI, Field.Url, "iface2.iq", gen feature("qyid") )
    terminalWhitelist("-1533470915", AccountType.IMEI, Field.Url, "api.meituan.com", gen feature("utm_content") )
    terminalWhitelist("1546841525", AccountType.IMEI, Field.Url, "nsclick.baidu.com", gen feature("c_openudid") )
    terminalWhitelist("1578054230", AccountType.IMEI, Field.Url, "iface2.iqi", gen feature("qyid") )
    terminalWhitelist("-1602878565", AccountType.IMEI, Field.Url, "susapi.lenovomm.com", gen feature("devid") )
    terminalWhitelist("-1615032258", AccountType.IMEI, Field.Url, "serv.vip.iqiyi.com", gen feature("id") )
    terminalWhitelist("1620434398", AccountType.IMEI, Field.Url, "temai.snssdk.com", gen feature("uuid") )
    terminalWhitelist("-1621087009", AccountType.IMEI, Field.Url, "i.meituan.com", gen feature("utm_content") )
    terminalWhitelist("1654203920", AccountType.IMEI, Field.Url, "adm.myzaker.com", gen feature("_udid") )
    terminalWhitelist("-1665953327", AccountType.IMEI, Field.Url, "sdkconfig.play.cp81.ott.cibntv.net", gen feature("imei") )
    terminalWhitelist("1667874873", AccountType.IMEI, Field.Url, "apis.dianhua.cn", gen feature("uid") )
    terminalWhitelist("1671458098", AccountType.IMEI, Field.Url, "config.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("-168866845", AccountType.IMEI, Field.Url, "api.t.iqiyi.com", gen feature("m_device_id") )
    terminalWhitelist("-1726897418", AccountType.IMEI, Field.Url, "iface2.iqiyi.com", gen feature("qyid") )
    terminalWhitelist("-1752207863", AccountType.IMEI, Field.Url, "spark.api.xiami.com", gen feature("device_id") )
    terminalWhitelist("-1755569995", AccountType.IMEI, Field.Url, "impservice.dictapp.youdao.com", gen feature("uid") )
    terminalWhitelist("-1756001625", AccountType.IMEI, Field.Cookie, "toutiao.com", gen feature("uuid") )
    terminalWhitelist("-1788082218", AccountType.IMEI, Field.Url, "serv.vip.iqiyi.com", gen feature("qyid") )
    terminalWhitelist("1794123236", AccountType.IMEI, Field.Url, "iface2.", gen feature("qyid") )
    terminalWhitelist("-1798658191", AccountType.IMEI, Field.Url, "ana.masky.biddingx.com", gen feature("imei") )
    terminalWhitelist("1804559626", AccountType.IMEI, Field.Url, "api.ycapp.yiche.com", gen feature("deviceid") )
    terminalWhitelist("1804906456", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("id") )
    terminalWhitelist("1822147635", AccountType.IMEI, Field.Url, "susapi.lenovomm.com", gen feature("sm2") )
    terminalWhitelist("1825752734", AccountType.IMEI, Field.Url, "dm.bytedance.com", gen feature("uuid") )
    terminalWhitelist("-1827879719", AccountType.IMEI, Field.Url, "cm.masky.biddingx.com", gen feature("mzid") )
    terminalWhitelist("1828269073", AccountType.IMEI, Field.Url, "api10.shuqireader.com", gen feature("imei") )
    terminalWhitelist("186422481", AccountType.IMEI, Field.Url, "user.api.3g.youku.com", gen feature("imei") )
    terminalWhitelist("-1883096106", AccountType.IMEI, Field.Url, "mbdlog.iqiyi.com", gen feature("qyid") )
    terminalWhitelist("1887514117", AccountType.IMEI, Field.Url, "mapvectors.map.qq.com", gen feature("imei") )
    terminalWhitelist("-189677929", AccountType.IMEI, Field.Url, "hd.api.mobile.youku.com", gen feature("imei") )
    terminalWhitelist("-1904562090", AccountType.IMEI, Field.Url, "iface2.i", gen feature("qyid") )
    terminalWhitelist("1908243069", AccountType.IMEI, Field.Url, "sc.appvipshop.com", gen feature("imei") )
    terminalWhitelist("1912469928", AccountType.IMEI, Field.Url, "busybox.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("1919998581", AccountType.IMEI, Field.Url, "s.go.sohu.com", gen feature("imei") )
    terminalWhitelist("-1920913424", AccountType.IMEI, Field.Url, "api.weibo.cn", gen feature("did") )
    terminalWhitelist("-1928297112", AccountType.IMEI, Field.Url, "w.51tv.com", gen feature("deviceId") )
    terminalWhitelist("-1933693045", AccountType.IMEI, Field.Url, "tq.91.com", gen feature("imei") )
    terminalWhitelist("-1941026159", AccountType.IMEI, Field.Url, "api.3g.tudou.com", gen feature("imei") )
    terminalWhitelist("1953661286", AccountType.IMEI, Field.Url, "bgstat.myzaker.com", gen feature("_udid") )
    terminalWhitelist("-1954692493", AccountType.IMEI, Field.Url, "api.map.baidu.com", gen feature("imei") )
    terminalWhitelist("-1973865263", AccountType.IMEI, Field.Url, "logic.content.qq.com", gen feature("imei") )
    terminalWhitelist("-1989667807", AccountType.IMEI, Field.Url, "ex.puata.info", gen feature("device_id") )
    terminalWhitelist("-2014648527", AccountType.IMEI, Field.Url, "114.80.165.113", gen feature("imei") )
    terminalWhitelist("-2045906603", AccountType.IMEI, Field.Cookie, "is.snssdk.com", gen feature("uuid") )
    terminalWhitelist("2055629046", AccountType.IMEI, Field.Url, "iface2", gen feature("qyid") )
    terminalWhitelist("-2064648920", AccountType.IMEI, Field.Url, "w.m.taobao.com", gen feature("deviceid") )
    terminalWhitelist("206615099", AccountType.IMEI, Field.Url, "mcgi.v.qq.com", gen feature("device_id") )
    terminalWhitelist("-2078453631", AccountType.IMEI, Field.Url, "ad.api.3g.youku.com", gen feature("imei") )
    terminalWhitelist("2101462963", AccountType.IMEI, Field.Url, "sax.sina.com.cn", gen feature("userid") )
    terminalWhitelist("-2111980555", AccountType.IMEI, Field.Url, "ark.letv.com", gen feature("im") )
    terminalWhitelist("2139440094", AccountType.IMEI, Field.Url, "ic.snssdk.com", gen feature("uuid") )
    terminalWhitelist("215746911", AccountType.IMEI, Field.Url, "v.map.baidu.com", gen feature("im") )
    terminalWhitelist("-217417551", AccountType.IMEI, Field.Url, "aa1.pub.funshion.com", gen feature("imei") )
    terminalWhitelist("230971491", AccountType.IMEI, Field.Url, "g.cn.miaozhen.com", gen feature("imei") )
    terminalWhitelist("-24183279", AccountType.IMEI, Field.Url, "sdkconfig.video.qq.com", gen feature("imei") )
    terminalWhitelist("242820372", AccountType.IMEI, Field.Url, "g.cn.miaozhen.com", gen feature("cUDID") )
    terminalWhitelist("322598760", AccountType.IMEI, Field.Url, "serv.vip.iqiyi.com", gen feature("deviceID") )
    terminalWhitelist("336301489", AccountType.IMEI, Field.Url, "app.ymatou.com", gen feature("imei") )
    terminalWhitelist("-36340287", AccountType.IMEI, Field.Url, "ad.api.3g.tudou.com", gen feature("imei") )
    terminalWhitelist("-366424810", AccountType.IMEI, Field.Url, "log.ycapp.yiche.com", gen feature("deviceId") )
    terminalWhitelist("-385390073", AccountType.IMEI, Field.Url, "dict.youdao.com", gen feature("imei") )
    terminalWhitelist("386934922", AccountType.IMEI, Field.Url, "ipip.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("-420704554", AccountType.IMEI, Field.Url, "i", gen feature("qyid") )
    terminalWhitelist("429751028", AccountType.IMEI, Field.Url, "sns.myzaker.com", gen feature("_udid") )
    terminalWhitelist("442357795", AccountType.IMEI, Field.Url, "i.waimai.meituan.com", gen feature("wm_did") )
    terminalWhitelist("442401447", AccountType.IMEI, Field.Url, "subscription.iqiyi.com", gen feature("ckuid") )
    terminalWhitelist("460120501", AccountType.IMEI, Field.Url, "api.mobile.youku.com", gen feature("im") )
    terminalWhitelist("48288137", AccountType.IMEI, Field.Url, "i.go.sohu.com", gen feature("imei") )
    terminalWhitelist("490302333", AccountType.IMEI, Field.Url, "api.cupid.iqiyi.com", gen feature("n") )
    terminalWhitelist("-509376704", AccountType.IMEI, Field.Url, "adx.autohome.com.cn", gen feature("dvid") )
    terminalWhitelist("509684085", AccountType.IMEI, Field.Url, "api.meituan.com", gen feature("devid") )
    terminalWhitelist("-520398281", AccountType.IMEI, Field.Url, "commdata.v.qq.com", gen feature("device_id") )
    terminalWhitelist("-522035343", AccountType.IMEI, Field.Url, "val.atm.youku.com", gen feature("im") )
    terminalWhitelist("-548027562", AccountType.IMEI, Field.Url, "ifac", gen feature("qyid") )
    terminalWhitelist("550528518", AccountType.IMEI, Field.Url, "api.anjuke.com", gen feature("i") )
    terminalWhitelist("567233089", AccountType.IMEI, Field.Url, "mcgi.v.qq.com", gen feature("imei") )
    terminalWhitelist("582673484", AccountType.IMEI, Field.Url, "i.vip.iqiyi.com", gen feature("qyid") )
    terminalWhitelist("586037983", AccountType.IMEI, Field.Url, "user-mobile.youku.com", gen feature("imei") )
    terminalWhitelist("-614724298", AccountType.IMEI, Field.Url, "log.ycapp.yiche.com", gen feature("deviceid") )
    terminalWhitelist("617680177", AccountType.IMEI, Field.Url, "tp.coolmart.net.cn", gen feature("imei") )
    terminalWhitelist("-634578595", AccountType.IMEI, Field.Url, "api.changba.com", gen feature("imei") )
    terminalWhitelist("-638306669", AccountType.IMEI, Field.Url, "mapi.dianping.com", gen feature("imei") )
    terminalWhitelist("-642991639", AccountType.IMEI, Field.Url, "config.push.sogou.com", gen feature("udid") )
    terminalWhitelist("-652577328", AccountType.IMEI, Field.Url, "toutiao.com", gen feature("uuid") )
    terminalWhitelist("656258278", AccountType.IMEI, Field.Url, "iphone.myzaker.com", gen feature("_udid") )
    terminalWhitelist("668977127", AccountType.IMEI, Field.Url, "iface2.iqiyi.com", gen feature("dev_imei") )
    terminalWhitelist("673068337", AccountType.IMEI, Field.Url, "albs.moji001.com", gen feature("IMEI") )
    terminalWhitelist("673598504", AccountType.IMEI, Field.Url, "dispatcher.camera360.com", gen feature("deviceId") )
    terminalWhitelist("691953029", AccountType.IMEI, Field.Url, "data.video.qiyi.com", gen feature("su") )
    terminalWhitelist("707366280", AccountType.IMEI, Field.Url, "w.51tv.com", gen feature("deviceid") )
    terminalWhitelist("-707767531", AccountType.IMEI, Field.Cookie, "i.snssdk.com", gen feature("uuid") )
    terminalWhitelist("717593512", AccountType.IMEI, Field.Url, "app.ymatou.com", gen feature("deviceid") )
    terminalWhitelist("717812060", AccountType.IMEI, Field.Url, "bid.adview.cn", gen feature("ud") )
    terminalWhitelist("-735553813", AccountType.IMEI, Field.Url, "wlan.ct10000.com", gen feature("device_id") )
    terminalWhitelist("-750802619", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("device_id") )
    terminalWhitelist("756666160", AccountType.IMEI, Field.Url, "v2.yundzh.com", gen feature("deviceid") )
    terminalWhitelist("756768469", AccountType.IMEI, Field.Url, "show.m.mediav.com", gen feature("imei") )
    terminalWhitelist("-770247343", AccountType.IMEI, Field.Url, "api.mobile.youku.com", gen feature("imei") )
    terminalWhitelist("770650922", AccountType.IMEI, Field.Url, "api.cupid.iqiyi.com", gen feature("a") )
    terminalWhitelist("-785604616", AccountType.IMEI, Field.Url, "iface.iqiyi.com", gen feature("uuid") )
    terminalWhitelist("-796011627", AccountType.IMEI, Field.Url, "apple.www.letv.com", gen feature("im") )
    terminalWhitelist("-798762287", AccountType.IMEI, Field.Url, "social-api.meilishuo.com", gen feature("imei") )
    terminalWhitelist("-822612596", AccountType.IMEI, Field.Url, "tuijian.suning.com", gen feature("c") )
    terminalWhitelist("-840166091", AccountType.IMEI, Field.Cookie, "ic.snssdk.com", gen feature("uuid") )
    terminalWhitelist("842824640", AccountType.IMEI, Field.Url, "update.kakamobi.com", gen feature("_imei") )
    terminalWhitelist("852566612", AccountType.IMEI, Field.Url, "susapi.lenovomm.com", gen feature("sm1") )
    terminalWhitelist("-875795061", AccountType.IMEI, Field.Url, "api.sina.cn", gen feature("imei") )
    terminalWhitelist("-882080838", AccountType.IMEI, Field.Url, "a3.pstatp.com", gen feature("uuid") )
    terminalWhitelist("-885076287", AccountType.IMEI, Field.Url, "api.didialift.com", gen feature("imei") )
    terminalWhitelist("-905299311", AccountType.IMEI, Field.Url, "tj.coolyun.com", gen feature("imei") )
    terminalWhitelist("906846126", AccountType.IMEI, Field.Url, "mb.hd.sohu.com.cn", gen feature("pid") )
    terminalWhitelist("-914153882", AccountType.IMEI, Field.Url, "www.qchannel02.cn", gen feature("did") )
    terminalWhitelist("921822984", AccountType.IMEI, Field.Url, "m.api.dianping.com", gen feature("deviceid") )
    terminalWhitelist("933699582", AccountType.IMEI, Field.Url, "is.snssdk.com", gen feature("uuid") )
    terminalWhitelist("-973651984", AccountType.IMEI, Field.Url, "ipservice.mogujie.com", gen feature("did") )
    terminalWhitelist("986702894", AccountType.IMEI, Field.Url, "e.dangdang.com", gen feature("deviceSerialNo") )
    terminalWhitelist("988680511", AccountType.IMEI, Field.Url, "d.meilishuo.com", gen feature("_did") )

    //idfa  all
    terminalWhitelist("-1400974010", AccountType.IDFA, Field.Url, "log.waimai.baidu.com", gen feature("idfa") )
    terminalWhitelist("1599107464", AccountType.IDFA, Field.Url, "mapi.dianping.com", gen feature("idfa") )
    terminalWhitelist("1656484824", AccountType.IDFA, Field.Url, "a3.bytecdn.cn", gen feature("idfa") )
    terminalWhitelist("-1673794554", AccountType.IDFA, Field.Url, "api.3g.tudou.com", gen feature("idfa") )
    terminalWhitelist("1724708342", AccountType.IDFA, Field.Url, "ad.api.3g.youku.com", gen feature("idfa") )
    terminalWhitelist("176108259", AccountType.IDFA, Field.Url, "www.xiaohongshu.com", gen feature("deviceId") )
    terminalWhitelist("1810501984", AccountType.IDFA, Field.Url, "isub.snssdk.com", gen feature("idfa") )
    terminalWhitelist("-1820967682", AccountType.IDFA, Field.Url, "i.go.sohu.com", gen feature("idfa") )
    terminalWhitelist("188088150", AccountType.IDFA, Field.Url, "service.cocounion.com", gen feature("idfa") )
    terminalWhitelist("-1898646810", AccountType.IDFA, Field.Url, "ichannel.snssdk.com", gen feature("idfa") )
    terminalWhitelist("1949957990", AccountType.IDFA, Field.Url, "service.inke.com", gen feature("idfa") )
    terminalWhitelist("1982051970", AccountType.IDFA, Field.Url, "val.atm.youku.com", gen feature("idfa") )
    terminalWhitelist("2013583120", AccountType.IDFA, Field.Url, "api3g2.lvmama.com", gen feature("lvidfa") )
    terminalWhitelist("2039614854", AccountType.IDFA, Field.Url, "agn.aty.sohu.com", gen feature("idfa") )
    terminalWhitelist("2144698714", AccountType.IDFA, Field.Url, "gm.mmstat.com", gen feature("idfa") )
    terminalWhitelist("306378758", AccountType.IDFA, Field.Url, "afpssp.alimama.com", gen feature("idfa") )
    terminalWhitelist("-322598398", AccountType.IDFA, Field.Url, "dm.api.3g.tudou.com", gen feature("idfa") )
    terminalWhitelist("-345733626", AccountType.IDFA, Field.Url, "adapi.hiwemeet.com", gen feature("idfa") )
    terminalWhitelist("387802182", AccountType.IDFA, Field.Url, "so.ard.iyyin.com", gen feature("idfa") )
    terminalWhitelist("-461368522", AccountType.IDFA, Field.Url, "ad.api.3g.tudou.com", gen feature("idfa") )
    terminalWhitelist("513056934", AccountType.IDFA, Field.Url, "114.80.165.113", gen feature("idfa") )
    terminalWhitelist("562192084", AccountType.IDFA, Field.Url, "user-mobile.youku.com", gen feature("idfa") )
    terminalWhitelist("-627502590", AccountType.IDFA, Field.Url, "a3.pstatp.com", gen feature("idfa") )
    terminalWhitelist("-633849442", AccountType.IDFA, Field.Url, "a6.bytecdn.cn", gen feature("idfa") )
    terminalWhitelist("-666551838", AccountType.IDFA, Field.Url, "i.play.api.3g.youku.com", gen feature("idfa") )
    terminalWhitelist("-688429370", AccountType.IDFA, Field.Url, "api.mobile.youku.com", gen feature("idfa") )
    terminalWhitelist("705325515", AccountType.IDFA, Field.Url, "adm.myzaker.com", gen feature("_idfa") )
    terminalWhitelist("708377894", AccountType.IDFA, Field.Url, "ai1.pub.funshion.com", gen feature("idfa") )
    terminalWhitelist("-833984790", AccountType.IDFA, Field.Url, "s.go.sohu.com", gen feature("idfa") )
    terminalWhitelist("856772259", AccountType.IDFA, Field.Cookie, "cdnimg.ocj.com.cn", gen feature("idfa") )
    terminalWhitelist("-858514788", AccountType.IDFA, Field.Url, "impservice.dictapp.youdao.com", gen feature("idfa") )
    terminalWhitelist("-927358336", AccountType.IDFA, Field.Url, "api.sina.cn", gen feature("idfa") )
    terminalWhitelist("-1268691409", AccountType.IDFA, Field.Url, "logic.content.qq.com", gen feature("imei") )
    terminalWhitelist("-36295967", AccountType.IDFA, Field.Url, "api.mob.app.letv.com", gen feature("devid") )
    terminalWhitelist("376432045", AccountType.IDFA, Field.Url, "apple.www.letv.com", gen feature("device_id") )
    terminalWhitelist("402731531", AccountType.IDFA, Field.Url, "spark.api.xiami.com", gen feature("device_id") )
    terminalWhitelist("46598401", AccountType.IDFA, Field.Url, "ic.snssdk.com", gen feature("idfa") )
    terminalWhitelist("513620609", AccountType.IDFA, Field.Url, "ad.51wnl.com", gen feature("idfa") )
    terminalWhitelist("-694719251", AccountType.IDFA, Field.Url, "serv.vip.iqiyi.com", gen feature("device_id") )

    terminalWhitelist("1386775664", AccountType.IDFA, Field.Url, "qq.irs01.com", gen feature("idfa") notContains("%"))
    terminalWhitelist("-1855563760", AccountType.IDFA, Field.Url, "lf.snssdk.com", gen feature("idfa") notContains("%"))
    terminalWhitelist("-1869636336", AccountType.IDFA, Field.Url, "iface.iqiyi.com", gen feature("cupid_uid") notContains("%"))
    terminalWhitelist("-525195690", AccountType.IDFA, Field.Url, "upmobile.v.qq.com", gen feature("device_id") notContains("%"))
    terminalWhitelist("585300956", AccountType.IDFA, Field.Url, "iface2.iqiyi.com", gen feature("device_id") notContains("%"))
    terminalWhitelist("-700361178", AccountType.IDFA, Field.Url, "irs01.com", gen feature("idfa") notContains("%"))
    //mdn
    terminalWhitelist("-1345609291", AccountType.MDN, Field.Url, "as.xiaojukeji.com", gen feature("phone") regex())
    terminalWhitelist("1476998758", AccountType.MDN, Field.Url, "114.80.165.113", gen feature("phoneno") regex())
    terminalWhitelist("1566887076", AccountType.MDN, Field.Cookie, "i.meituan.com", gen feature("h_cookie_phone") regex())
    terminalWhitelist("-1644161052", AccountType.MDN, Field.Cookie, "4g.if.qidian.com", gen feature("stat_sessid") regex())
    terminalWhitelist("-1654898857", AccountType.MDN, Field.Url, "youyuan.com", gen feature("MOBILE") regex())
    terminalWhitelist("-1843282568", AccountType.MDN, Field.Cookie, "m.client.10010.com", gen feature("c_mobile") regex())
    terminalWhitelist("-1881989153", AccountType.MDN, Field.Url, "api.diditaxi.com.cn", gen feature("usr") regex())
    terminalWhitelist("-1921340011", AccountType.MDN, Field.Url, "api.anjuke.com", gen feature("broker_phone") regex())
    terminalWhitelist("1970071167", AccountType.MDN, Field.Url, "m.baidu.com", gen feature("phone") regex())
    terminalWhitelist("-200991877", AccountType.MDN, Field.Url, "laoshi.gaodun.com", gen feature("phone") regex())
    terminalWhitelist("-20354394", AccountType.MDN, Field.Url, "www.dianping.com", gen feature("phoneNo") regex())
    terminalWhitelist("-237044608", AccountType.MDN, Field.Url, "api.diditaxi.com.cn", gen feature("d_phone") regex())
    terminalWhitelist("287988391", AccountType.MDN, Field.Url, "www.hepandai.com", gen feature("phone") regex())
    terminalWhitelist("414456457", AccountType.MDN, Field.Url, "www.58caifu.cn", gen feature("mobilePhone") regex())
    terminalWhitelist("554472173", AccountType.MDN, Field.Url, "wap.wandafilm.com", gen feature("mobile") regex())
    terminalWhitelist("614239454", AccountType.MDN, Field.Cookie, "imgsize.52shangou.com", gen feature("redcat_user_mobile") regex())
    terminalWhitelist("79546825", AccountType.MDN, Field.Url, "creditcard.bankcomm.com", gen feature("mobile_no") regex())
    terminalWhitelist("-96081290", AccountType.MDN, Field.Cookie, "ios4g.if.qidian.com", gen feature("stat_sessid") regex())
    terminalWhitelist("972151968", AccountType.MDN, Field.Url, "api.udache.com", gen feature("phone_num") regex())
    terminalWhitelist("1268746412", AccountType.MDN, Field.Url, "imall.diditaxi.com.cn", gen feature("phone") regex())
    terminalWhitelist("1277201935", AccountType.MDN, Field.Url, "www.sh.10086.cn", gen feature("WT.mobile") regex())
    terminalWhitelist("1284137956", AccountType.MDN, Field.Cookie, "www.weibo.com", gen feature("un") regex())
    terminalWhitelist("1291777227", AccountType.MDN, Field.Url, "weibo.com", gen feature("value") regex())
    terminalWhitelist("-1294610443", AccountType.MDN, Field.Cookie, "www.vip.com", gen feature("VipRNAME") regex())
    terminalWhitelist("-1335427479", AccountType.MDN, Field.Cookie, "t7z.cupid.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("1344958595", AccountType.MDN, Field.Cookie, "apple.www.letv.com", gen feature("loginname") regex())
    terminalWhitelist("1352726984", AccountType.MDN, Field.Url, "i.waimai.meituan.com", gen feature("user_phone") regex())
    terminalWhitelist("-1357591286", AccountType.MDN, Field.Cookie, "stat.10jqka.com.cn", gen feature("u_name") regex())
    terminalWhitelist("-1375659356", AccountType.MDN, Field.Url, "api.udache.com", gen feature("phone") regex())
    terminalWhitelist("138790231", AccountType.MDN, Field.Cookie, "search.yhd.com", gen feature("ac") regex())
    terminalWhitelist("1410387034", AccountType.MDN, Field.Cookie, "guba.eastmoney.com", gen feature("pu") regex())
    terminalWhitelist("-1415891068", AccountType.MDN, Field.Url, "conf.diditaxi.com.cn", gen feature("phone") regex())
    terminalWhitelist("1422352419", AccountType.MDN, Field.Cookie, "e.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-1435106961", AccountType.MDN, Field.Cookie, "tuijian.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("-1485367413", AccountType.MDN, Field.Cookie, "serv.vip.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("1532018278", AccountType.MDN, Field.Url, "api.diditaxi.com.cn", gen feature("phone") regex())
    terminalWhitelist("-1541980900", AccountType.MDN, Field.Url, "ws2.cootekservice.com", gen feature("contactname") regex())
    terminalWhitelist("-1546756945", AccountType.MDN, Field.Url, "mapi.appvipshop.com", gen feature("user_name") regex())
    terminalWhitelist("1569140894", AccountType.MDN, Field.Url, "mapi.appvipshop.com", gen feature("username") regex())
    terminalWhitelist("-1589392109", AccountType.MDN, Field.Cookie, "serv.vip.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("161176010", AccountType.MDN, Field.Cookie, "eq.10jqka.com.cn", gen feature("u_name") regex())
    terminalWhitelist("1614431723", AccountType.MDN, Field.Cookie, "iface2.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("1623055729", AccountType.MDN, Field.Cookie, "api.yuedu.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("167063331", AccountType.MDN, Field.Cookie, "ark.letv.com", gen feature("loginname") regex())
    terminalWhitelist("-1703938008", AccountType.MDN, Field.Cookie, "i.waimai.meituan.com", gen feature("cookie_phone") regex())
    terminalWhitelist("-1712072718", AccountType.MDN, Field.Cookie, "m.client.10010.com", gen feature("u_account") regex())
    terminalWhitelist("-1717643709", AccountType.MDN, Field.Url, "eq.10jqka.com.cn", gen feature("account") regex())
    terminalWhitelist("-1719840135", AccountType.MDN, Field.Cookie, "iface.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("-1751943255", AccountType.MDN, Field.Cookie, "xray.jebe.renren.com", gen feature("ln_uact") regex())
    terminalWhitelist("-1759978978", AccountType.MDN, Field.Cookie, "hd.api.mobile.youku.com", gen feature("u") regex())
    terminalWhitelist("1770339990", AccountType.MDN, Field.Cookie, "www.iqiyi.com", gen feature("user_name") regex())
    terminalWhitelist("1791423748", AccountType.MDN, Field.Url, "client.3g.fang.com", gen feature("phone") regex())
    terminalWhitelist("-1797881987", AccountType.MDN, Field.Cookie, "i.waimai.meituan.com", gen feature("grap_cookie_phone_ab") regex())
    terminalWhitelist("1824503847", AccountType.MDN, Field.Cookie, "apple.www.letv.com", gen feature("loginnamecookie") regex())
    terminalWhitelist("-182559100", AccountType.MDN, Field.Url, "static.diditaxi.com.cn", gen feature("phone") regex())
    terminalWhitelist("-1829051589", AccountType.MDN, Field.Cookie, "search.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("1839080344", AccountType.MDN, Field.Url, "www.sh.10086.cn", gen feature("telno") regex())
    terminalWhitelist("1843778356", AccountType.MDN, Field.Url, "checkout.vip.com", gen feature("userId") regex())
    terminalWhitelist("-1854709781", AccountType.MDN, Field.Cookie, "file.yuedu.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("-1877336693", AccountType.MDN, Field.Cookie, "subscription.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("-1892150385", AccountType.MDN, Field.Cookie, "l.rcd.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("191321781", AccountType.MDN, Field.Cookie, "cart.vip.com", gen feature("VipRNAME") regex())
    terminalWhitelist("1934991595", AccountType.MDN, Field.Cookie, "dc.letv.com", gen feature("loginname") regex())
    terminalWhitelist("-1946787813", AccountType.MDN, Field.Cookie, "www.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("1960309296", AccountType.MDN, Field.Url, "app.veryzhun.com", gen feature("mobile") regex())
    terminalWhitelist("199875139", AccountType.MDN, Field.Cookie, "www.le.com", gen feature("loginname") regex())
    terminalWhitelist("-2006451740", AccountType.MDN, Field.Url, "common.diditaxi.com.cn", gen feature("phone") regex())
    terminalWhitelist("2037081535", AccountType.MDN, Field.Cookie, "s.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-2054735024", AccountType.MDN, Field.Url, "api.3g.tudou.com", gen feature("mobile") regex())
    terminalWhitelist("2057084887", AccountType.MDN, Field.Cookie, "shop.yhd.com", gen feature("ac") regex())
    terminalWhitelist("2067822019", AccountType.MDN, Field.Cookie, "selector.webp2p.letv.com", gen feature("loginname") regex())
    terminalWhitelist("-2083106695", AccountType.MDN, Field.Cookie, "ubt0.fanli.com", gen feature("prousernameutf") regex())
    terminalWhitelist("20870953", AccountType.MDN, Field.Cookie, "www.sh.10086.cn", gen feature("loginName") regex())
    terminalWhitelist("-2095880345", AccountType.MDN, Field.Cookie, "selector.webp2p.letv.com", gen feature("loginnamecookie") regex())
    terminalWhitelist("-2101279807", AccountType.MDN, Field.Cookie, "eq.10jqka.com.cn", gen feature("escapename") regex())
    terminalWhitelist("2128891376", AccountType.MDN, Field.Url, "i.vaakwe.com", gen feature("mobile") regex())
    terminalWhitelist("-214527918", AccountType.MDN, Field.Cookie, "weibo.com", gen feature("un") regex())
    terminalWhitelist("231132879", AccountType.MDN, Field.Cookie, "www.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("236961515", AccountType.MDN, Field.Cookie, "act.vip.com", gen feature("VipRNAME") regex())
    terminalWhitelist("249363359", AccountType.MDN, Field.Cookie, "shop.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("-256387343", AccountType.MDN, Field.Cookie, "iface.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("268034197", AccountType.MDN, Field.Cookie, "i.vip.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("-30938891", AccountType.MDN, Field.Cookie, "category.vip.com", gen feature("VipRNAME") regex())
    terminalWhitelist("-309395597", AccountType.MDN, Field.Cookie, "iface2.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("324813097", AccountType.MDN, Field.Url, "sdc.10086.cn", gen feature("WT.mobile") regex())
    terminalWhitelist("-3345507", AccountType.MDN, Field.Url, "click.suning.cn", gen feature("loginUserName") regex())
    terminalWhitelist("-379205211", AccountType.MDN, Field.Cookie, "api.t.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("386059637", AccountType.MDN, Field.Cookie, "www.sh.10086.cn", gen feature("MEMBER_ID") regex())
    terminalWhitelist("-40080479", AccountType.MDN, Field.Cookie, "category.vip.com", gen feature("login_username") regex())
    terminalWhitelist("-403528266", AccountType.MDN, Field.Cookie, "m.autohome.com.cn", gen feature("orderuserphonenew") regex())
    terminalWhitelist("408281235", AccountType.MDN, Field.Cookie, "www.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("-416194501", AccountType.MDN, Field.Cookie, "shopping.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("425681035", AccountType.MDN, Field.Cookie, "info.vip.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("-428697593", AccountType.MDN, Field.Cookie, "l.rcd.iqiyi.com", gen feature("P000email") regex())
    terminalWhitelist("438999336", AccountType.MDN, Field.Cookie, "api.m.mtime.cn", gen feature("loginEmail") regex())
    terminalWhitelist("-460637702", AccountType.MDN, Field.Url, "soufunapp.3g.fang.com", gen feature("mobile") regex())
    terminalWhitelist("497451058", AccountType.MDN, Field.Cookie, "ubt0.fanli.com", gen feature("prousername") regex())
    terminalWhitelist("-513270546", AccountType.MDN, Field.Url, "soufunapp.3g.fang.com", gen feature("phone") regex())
    terminalWhitelist("-530482783", AccountType.MDN, Field.Cookie, "www.vip.com", gen feature("login_username") regex())
    terminalWhitelist("551845892", AccountType.MDN, Field.Url, "de.as.pptv.com", gen feature("username") regex())
    terminalWhitelist("562992040", AccountType.MDN, Field.Url, "sc.appvipshop.com", gen feature("userid") regex())
    terminalWhitelist("-565426622", AccountType.MDN, Field.Url, "irs01.com", gen feature("dn") regex())
    terminalWhitelist("-567453962", AccountType.MDN, Field.Cookie, "www.ceair.com", gen feature("ffpno") regex())
    terminalWhitelist("-574996935", AccountType.MDN, Field.Url, "mapi.appvipshop.com", gen feature("login_id") regex())
    terminalWhitelist("583109078", AccountType.MDN, Field.Url, "m.ctrip.com", gen feature("userid") regex())
    terminalWhitelist("597050529", AccountType.MDN, Field.Cookie, "checkout.vip.com", gen feature("login_username") regex())
    terminalWhitelist("606192117", AccountType.MDN, Field.Cookie, "checkout.vip.com", gen feature("VipRNAME") regex())
    terminalWhitelist("-611710147", AccountType.MDN, Field.Cookie, "sale.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("616352531", AccountType.MDN, Field.Cookie, "subscription.iqiyi.com", gen feature("QC116") regex())
    terminalWhitelist("621893519", AccountType.MDN, Field.Cookie, "dc.letv.com", gen feature("loginnamecookie") regex())
    terminalWhitelist("641068929", AccountType.MDN, Field.Cookie, "www.dianping.com", gen feature("ua") regex())
    terminalWhitelist("652419364", AccountType.MDN, Field.Url, "user.qunar.com", gen feature("username") regex())
    terminalWhitelist("675399215", AccountType.MDN, Field.Cookie, "mar.vip.com", gen feature("login_username") regex())
    terminalWhitelist("699066855", AccountType.MDN, Field.Cookie, "www.le.com", gen feature("loginnamecookie") regex())
    terminalWhitelist("763600639", AccountType.MDN, Field.Url, "click.suning.cn", gen feature("lu") regex())
    terminalWhitelist("772715952", AccountType.MDN, Field.Url, "www.ganji.com", gen feature("phone") regex())
    terminalWhitelist("78595425", AccountType.MDN, Field.Cookie, "cart.vip.com", gen feature("login_username") regex())
    terminalWhitelist("802246871", AccountType.MDN, Field.Cookie, "list.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-88728445", AccountType.MDN, Field.Cookie, "mar.vip.com", gen feature("VipRNAME") regex())
    terminalWhitelist("-89868655", AccountType.MDN, Field.Cookie, "cdnimg.ocj.com.cn", gen feature("loginid") regex())
    terminalWhitelist("-92857081", AccountType.MDN, Field.Cookie, "www.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-930555666", AccountType.MDN, Field.Cookie, "widget.weibo.com", gen feature("un") regex())
    terminalWhitelist("-960347997", AccountType.MDN, Field.Cookie, "th.suning.com", gen feature("idsLoginUserIdLastTime") regex())
    terminalWhitelist("-966189089", AccountType.MDN, Field.Cookie, "i.waimai.meituan.com", gen feature("h_cookie_phone") regex())
    terminalWhitelist("1340219081", AccountType.MDN, Field.Cookie, "fun.fanli.com", gen feature("prousername") regex())
    terminalWhitelist("1458925000", AccountType.MDN, Field.Cookie, "webim.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-1515640084", AccountType.MDN, Field.Cookie, "buy.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-1606634672", AccountType.MDN, Field.Cookie, "t.yhd.com", gen feature("ac") regex())
    terminalWhitelist("1871542614", AccountType.MDN, Field.Cookie, "h5.m.jd.com", gen feature("pt_pin") regex())
    terminalWhitelist("-1916331238", AccountType.MDN, Field.Cookie, "item.yhd.com", gen feature("ac") regex())
    terminalWhitelist("1994168358", AccountType.MDN, Field.Cookie, "cms.yhd.com", gen feature("ac") regex())
    terminalWhitelist("2010783362", AccountType.MDN, Field.Cookie, "item.yhd.com", gen feature("uname") regex())
    terminalWhitelist("-36468230", AccountType.MDN, Field.Cookie, "cart.yhd.com", gen feature("ac") regex())
    terminalWhitelist("-404320926", AccountType.MDN, Field.Cookie, "cart.yhd.com", gen feature("uname") regex())
    terminalWhitelist("-436169438", AccountType.MDN, Field.Cookie, "fun.fanli.com", gen feature("prousernameutf") regex())
    terminalWhitelist("508754003", AccountType.MDN, Field.Cookie, "h5.m.jd.com", gen feature("pwdt_id") regex())
    terminalWhitelist("780764795", AccountType.MDN, Field.Url, "k.sogou.com", gen feature("uid") regex())
    //email
    /*terminalWhitelist("964163634", AccountType.ANDROIDID, Field.Url, "api.sina.cn", gen feature("AndroidID") regex())*/
  }
}
